---
# Docker installation

- name: Install Docker on Ubuntu
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  block:
    - name: Create Docker directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG apt key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository for Ubuntu
      apt_repository:
        repo: >-
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

- name: Install Docker on Arch
  pacman:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Create Docker daemon configuration directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure Docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
          "dns": ["1.1.1.1", "1.0.0.1"]
      }
    mode: '0644'

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: true
